# Generated by Django 5.2.17 on 2026-10-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='joining_date',
            new_name='Joining_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='Salary',
        ),
    ]
