# Generated by Django 5.2.17 on 2026-10-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_address_employee_address_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=10)),
                ('Order_name', models.CharField(max_length=250)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
